CREATE OR REPLACE
PACKAGE PKGENTLIB_ARCHITECTURE
AS
type CURENTLIB_ARCHITECTURE
IS
  REF
  CURSOR;
END PKGENTLIB_ARCHITECTURE;
  ----------PKG BODY:------------------
/
CREATE OR REPLACE
PACKAGE BODY PKGENTLIB_ARCHITECTURE
AS
BEGIN
  DBMS_OUTPUT.PUT_LINE('OUTPUT');
END PKGENTLIB_ARCHITECTURE;
----------------------------------
/
CREATE OR REPLACE
PACKAGE TESTPACKAGE
AS
  PROCEDURE TEST_TRANS_CUST_DETAILS (
		p_customer_id		 	IN 			VARCHAR2,
	    cur_OUT 				OUT 		PKGENTLIB_ARCHITECTURE.CURENTLIB_ARCHITECTURE
	);
END TESTPACKAGE;
  ----------PKG BODY:------------------
/
CREATE OR REPLACE
PACKAGE BODY TESTPACKAGE
AS
	PROCEDURE TEST_TRANS_CUST_DETAILS
	(
		p_customer_id IN VARCHAR2,
	    cur_OUT OUT PKGENTLIB_ARCHITECTURE.CURENTLIB_ARCHITECTURE
	)
	AS
	BEGIN
	    OPEN cur_OUT FOR
		SELECT * 
		FROM Customers
		WHERE CustomerID = p_customer_id;

	END TEST_TRANS_CUST_DETAILS;
END TESTPACKAGE;
----------------------------------

