//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsuranceEntities : DbContext
    {
        public InsuranceEntities()
            : base("name=InsuranceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accident> Accidents { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<Claim> Claims { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<Policy> Policies { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserVehicle> UserVehicles { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<vAgentUser> vAgentUsers { get; set; }
    }
}
