//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAgentUser
    {
        public System.Guid UserId { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string FirstName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string SSN { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Data { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
